### ISSUE TITLE
关于训练结果

### ISSUE THREAD

**Issue by Quorafind** [Luka0612/cw2vec#1]
请问训练结果现在表现如何？

**Comment by Luka0612** [comment]
由于cw2vec涉及到对字符相似度的sum操作，训练起来比较久，而且还涉及一些超参数的调节，目前在训练&调节中，从中间输出的测试结果来过，效果还是可以期待下的

**Comment by Luka0612** [comment]
由于cw2vec涉及到对字符相似度的sum操作，训练起来比较久，而且还涉及一些超参数的调节，目前在训练&调节中，从中间输出的测试结果来过，效果还是可以期待下的

**Comment by dalinvip** [comment]
@Luka0612 请问，字符相似度的sum操作指的是什么？

**Comment by Luka0612** [comment]
@bamtercelboo [https://github.com/ShelsonCao/cw2vec/blob/master/cw2vec.pdf](url) 在sim(w,c)中，作者是采用w的所有stroke与c进行对相似度，然后求和。你可以详细看下2.2 objective function

**Comment by bamtercelboo** [comment]
@Luka0612 可以加一下我的QQ嘛（619472591）或者是给我一下你的联系方式，还有一些问题想请教一下，谢谢。

**Comment by daqiang2** [comment]
你好我下载好训练模型后导入的时候出错，提示模型中的normalized_embeddings大小为（3786，128）
