### ISSUE TITLE
基于字符向量训练疑惑请教

### ISSUE THREAD

**Issue by aslicedbread** [Luka0612/cw2vec#2]
如果使用gensim库中的word2vec，
假设有中文语料库A，进行基于字符训练词向量，word2vec中的输入应该是什么，A中包含的字符的一个集合作为输入还是说像进行词向量训练时类似，只是原来是分词，现在分字后的句子作为输入即可？

**Comment by Luka0612** [comment]
@aslicedbread 没用过gensim训练word2vec，word2vec是进行分词后将每个词作为单位输入，基于字符训练词向量是对词再进行细分成字符级别，然后将字符组合输入
