### ISSUE TITLE
非常感谢博主的分享。

### ISSUE THREAD

**Issue by zaczou** [Luka0612/cw2vec#3]
想文下有训练好的字符向量？还是是需要自己load好模型再提取处出来？提取出来的词向量矩阵怎么确保和word2id的索引对应上？

**Comment by Luka0612** [comment]
@zaczou 你自己尝试训练下再save词向量就可以了，这样你对词向量的理解会更加熟悉。词向量矩阵的index对应的就是wordid，这样你在训练过程中就能理解了
